default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: field-backend_development

test:
  <<: *default
  database: field-backend_test

production:
  <<: *default
  database: field-backend_production
  username: postgres
