default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reporter-backend_development

test:
  <<: *default
  database: reporter-backend_test

production:
  <<: *default
  database: reporter-backend_production
  username: postgres
