load "db/seeds/admin_user.rb"
load "db/seeds/user_interface_text.rb"
load "db/seeds/frontend_testing.rb"
load "db/seeds/water_pump.rb"
load "db/seeds/school_building.rb"
load "db/seeds/farming_workshop.rb"
load "db/seeds/covid_example.rb"
